### ISSUE TITLE
Node.js silent stop when prefixTest (and maybe setter text) has a slash in it

### ISSUE THREAD

**Issue by fraxken** [TopCli/Spinner#38]
When we create a Spinner with a prefixText that contains a slash Node.js silent stop with no warnings.

**Comment by JUSTIVE** [comment]
<img width="428" alt="image" src="https://github.com/TopCli/Spinner/assets/7118300/8212c234-21c4-411c-9117-507b3abdb41d">

Tested by running the spinner with a prefix containing a slash, it doesn't break at all. seems to be fixed at some moment before.

**Comment by fraxken** [comment]
Yes possible, code has been heaviliy refactored last few months.
